[hdsi_rba_ai_data_collection_kill_chain_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_rba_ai_data_collection_kill_chain_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
