[hdsi_ai_browser_extension_activity_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_browser_extension_activity_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
