[hdsi_ai_code_assistant_network_connection_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_code_assistant_network_connection_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
