[hdsi_ai_mcp_server_execution_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_mcp_server_execution_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
