[hdsi_ai_scripted_cli_invocation_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_scripted_cli_invocation_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
