[hdsi_ai_repeated_unsanctioned_access_burst_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_repeated_unsanctioned_access_burst_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
