[hdsi_ai_health_data_model_availability_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_health_data_model_availability_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
