[hdsi_ai_usage_volume_anomaly_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_usage_volume_anomaly_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
