[hdsi_ai_compromised_plugin_extension_installation_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_compromised_plugin_extension_installation_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
