[hdsi_ai_deepfake_tool_execution_access_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_deepfake_tool_execution_access_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
