[hdsi_ai_personal_email_to_ai_service_upload_correlation_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_personal_email_to_ai_service_upload_correlation_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
