[hdsi_ai_unsanctioned_desktop_app_execution_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_unsanctioned_desktop_app_execution_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
