version: 1.0.0
creation_date: '2026-03-04'
package_title: HDSI AI RBA Common Macros and Lookups
description: "Shared macros and lookup definitions used by all AI RBA detection packages. Must be deployed before any AI detection packages."
author: Hurricane Labs
app_compatibility:
  - app_name: SplunkEnterpriseSecuritySuite
    operator: '*'
    required_version: '*'
app_context: HurricaneLabsContentUpdates
enable_alerting: false
tags:
  - rba_only
deployment_type: global
