[hdsi_ai_high_volume_upload_to_ai_service_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_high_volume_upload_to_ai_service_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
