[hdsi_ai_voice_cloning_api_access_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_voice_cloning_api_access_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
