[hdsi_ai_access_via_vpn_proxy_evasion_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_access_via_vpn_proxy_evasion_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
