[hdsi_ai_unknown_high_volume_external_api_discovery_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_unknown_high_volume_external_api_discovery_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
