[hdsi_ai_api_key_exposure_in_code_dlp_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_api_key_exposure_in_code_dlp_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
