[hdsi_ai_llm_model_file_download_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_llm_model_file_download_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
