[hdsi_ai_local_llm_listening_port_detected_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_local_llm_listening_port_detected_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
