[hdsi_rba_ai_multi_vector_risk_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_rba_ai_multi_vector_risk_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
