[hdsi_ai_unsanctioned_web_access_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_unsanctioned_web_access_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
