[hdsi_ai_health_lookup_staleness_alert_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_health_lookup_staleness_alert_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
