[hdsi_ai_first_seen_provider_for_user_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_first_seen_provider_for_user_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
