[hdsi_ai_assisted_lateral_movement_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_assisted_lateral_movement_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
