[hdsi_ai_new_provider_adoption_velocity_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_new_provider_adoption_velocity_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
