[hdsi_ai_prompt_injection_indicators_in_web_uploads_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_prompt_injection_indicators_in_web_uploads_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
