[hdsi_template_detected_filter] #CHANGEME use this format for any search or where clauses. Empty prenthesis doesn't break anything just don't put "NOT `hdsi_template_filter`" that will break things
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_template_detected_customizations] #CHANGEME use this format for any other customizations you can use multiple search commands piping them together.
definition = search *
description = v1.0
disabled = False
iseval = 0
