[hdsi_rba_ai_privilege_escalation_correlation_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_rba_ai_privilege_escalation_correlation_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
