[hdsi_ai_dns_queries_to_ai_domains_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_dns_queries_to_ai_domains_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
