[hdsi_ai_sanctioned_dlp_violation_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_sanctioned_dlp_violation_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
