[hdsi_ai_api_access_from_non_dev_endpoint_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_api_access_from_non_dev_endpoint_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
