[hdsi_ai_access_from_unmanaged_device_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_access_from_unmanaged_device_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
