[hdsi_ai_dlp_violation_on_service_upload_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_dlp_violation_on_service_upload_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
