[hdsi_ai_usage_following_data_access_spike_filter]
definition = ()
description = v1.0
disabled = False
iseval = 0

[hdsi_ai_usage_following_data_access_spike_customizations]
definition = search *
description = v1.0
disabled = False
iseval = 0
